---
- name: Deploy HTML page in Apache Httpd container
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install prerequisites for Docker repository
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: Set up Docker stable repository
      shell: echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list

    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: present
        update_cache: yes

    - name: Install pip
      apt:
        pkg:
        - python3-pip
        update_cache: yes
        state: present

    - name: Install Docker SDK
      pip:
        name:
          - docker

    - name: Start Apache Httpd container
      docker_container:
        name: httpd
        image: httpd:latest
        state: started
        published_ports:
          - 80:80
        volumes:
          - /home/vagrant/html:/usr/local/apache2/htdocs/:ro



